language: node_js
node_js:
- node
script:
- npm install
- npm build
- printf '.gitignore\ndeployed*' > client/dist/.gitignore
- printf 'a17.martinmetodiev.com' > client/dist/CNAME
- cp 'README.md' client/dist
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: releases
  api_key:
    secure: XNu9wO+RzbudORchrn2AW2hV43dGWqRiuvuQOZaiBr8KwhpBcfMkRCWW8wTVmTUbrZE/NXso+Ym8NhB4BbDb8XzcGGcdMvTraMrqYnSIbrntNAm6ib7nGTOS/0i2AGMO1CbQk+jwNuov4NA6zIxqZTA1Uv6lWSFL0hWoGPziLfa4bk7iUKGAKKb95cqYVdtgRJ4MuP2e0tjUFxlCnIFZRkefMs+SFhERx2kEUnlabraMycTDJtqDRDsYWuvRDaKhxz8GJpVwLyFZMZTrZkFkBkBuR3b6Qn4RZ8NbGhLTjndlLYTkmfsocxCCwzYG/4RQnRdqjfNCZBc2iwSJda6/dixl5ZYuSDm0P2JeUai8U3Qx9yToLL3MlqBprEff+b4u9SaR1WRrkrRA5m1o3F8hgGwY4SJ8rVzfP9Hy7j1gIb8TI9FL939aWaYGZKkjM654UwpujHP0agPknDQWTPsknt2cVLwfQM/2MXr8URvH/hg6wpIypueNdIzI4TPtqPsLsyRMTamv7QaiuRgGwh9uRqkAef1vWajJ3v/7D7r2UZyaFhEYhpT3dD42EiVzBxcS3YcifhHNIbBykcLI2dQZ0hC15e6mIoO80eEulXFzgejCdD6nPb3U8Mc0TTskWAroPZvvaEC1zIxXQv0fbnGRVTaxNYqvHmMLAy2rvG0x+nw=
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  local_dir: client/dist
  target_branch: master
  github_token:
    secure: XNu9wO+RzbudORchrn2AW2hV43dGWqRiuvuQOZaiBr8KwhpBcfMkRCWW8wTVmTUbrZE/NXso+Ym8NhB4BbDb8XzcGGcdMvTraMrqYnSIbrntNAm6ib7nGTOS/0i2AGMO1CbQk+jwNuov4NA6zIxqZTA1Uv6lWSFL0hWoGPziLfa4bk7iUKGAKKb95cqYVdtgRJ4MuP2e0tjUFxlCnIFZRkefMs+SFhERx2kEUnlabraMycTDJtqDRDsYWuvRDaKhxz8GJpVwLyFZMZTrZkFkBkBuR3b6Qn4RZ8NbGhLTjndlLYTkmfsocxCCwzYG/4RQnRdqjfNCZBc2iwSJda6/dixl5ZYuSDm0P2JeUai8U3Qx9yToLL3MlqBprEff+b4u9SaR1WRrkrRA5m1o3F8hgGwY4SJ8rVzfP9Hy7j1gIb8TI9FL939aWaYGZKkjM654UwpujHP0agPknDQWTPsknt2cVLwfQM/2MXr8URvH/hg6wpIypueNdIzI4TPtqPsLsyRMTamv7QaiuRgGwh9uRqkAef1vWajJ3v/7D7r2UZyaFhEYhpT3dD42EiVzBxcS3YcifhHNIbBykcLI2dQZ0hC15e6mIoO80eEulXFzgejCdD6nPb3U8Mc0TTskWAroPZvvaEC1zIxXQv0fbnGRVTaxNYqvHmMLAy2rvG0x+nw=
  on:
    tags: true
